spring:
  # ?????? ?? ??
  datasource:
    url: jdbc:postgresql://localhost:5432/lotto  # STEP 3?? ?? DB ??
    username: lotto_id                            # STEP 3?? ?? ?? ??
    password: lotto_pw                        # STEP 3?? ??? ????
    driver-class-name: org.postgresql.Driver

  # JPA (Java Persistence API) ??
  jpa:
    hibernate:
      # ddl-auto: ?????? ?? ??? DB ???(??? ?)? ??? ?? ??
      #   - create: ?? ???? ???? ?? ?? (?? ?? ??? ??)
      #   - update: ??? ??? ??
      #   - validate: ???? ???? ?? ?????? ??
      #   - none: ???? ?? ?? (?? ???? ??)
      ddl-auto: create
    properties:
      hibernate:
        # ??? JPA? ???? SQL ??? ???
        show_sql: true
        # SQL ??? ?? ?? ???
        format_sql: true
        # ?? ??? ??? ?? (PostgreSQL?? user?? ??? ??? ??? ??? ??)
        default_schema: public
    # ?????? ??? ????? ??
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# ?? ?? ?? (JPA ?? ???? ?? ??? ???)
logging:
  level:
    org.hibernate.type.descriptor.sql: trace